
services:
  booking_service:
    build:
      context: ./BookingService
    container_name: booking_service
    restart: always
    ports:
      - "4000:4000"
    env_file:
    - './BookingService/.env'    
    depends_on:
      - booking_db
      - rabbitmq
    networks:
      - net  
  
  notification_service:
    build:
      context: ./NotificationService
    container_name: notification_service
    restart: always
    ports:
      - "4002:4002"
    env_file:
    - './NotificationService/.env'
    depends_on:
      - booking_db
      - rabbitmq
    networks:
      - net  
          
  
  booking_db:
    image: mysql
    container_name: booking_db
    environment:
      MYSQL_ROOT_PASSWORD: Keshav/043
      MYSQL_DATABASE: Flights
    ports:
      - "3306:3306"
    networks:
      - net    


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # main RabbitMQ messaging port
      - "15672:15672"   # management UI
    networks:
      - net

 
networks:
  net: