const SEAT_TYPE = {
    BUSINESS: 'BUSINESS',
    ECONOMY: 'ECONOMY',
    PREMIUM_ECONOMY: 'PREMIUM ECONOMY',
    FIRST_CLASS: 'FIRST CLASS'
}

const BOOKING_status = {
    PENDING: 'PENDING',
    INITIATED: 'INITIATED',
    CANCELLED: 'CANCELLED',
    BOOKED: 'BOOKED'
}

const TICKET_STATUS = {
    ISSUED: "ISSUED",
    CANCELLED: "CANCELLED",
    CHECKED_IN: "CHECKED_IN"
}

module.exports = {
    SEAT_TYPE,
    BOOKING_status,
    TICKET_STATUS
}